# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Frame Check
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - toc.integrate
    - toc.follow
  palette:
    # Palette toggle for automatic mode

    - media: "(prefers-color-scheme)"
      primary: deep orange
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep orange
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep orange
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
  - Home: index.md
  - Editor Integrations: editor.md
  - Features:
      - summary.md
      - features/index.md
      - features/column_assignment_methods.md
      - features/column_removal_methods.md
      - features/dataframe_creation_methods.md
      - features/edge_cases.md

plugins:
  - search:
      enabled: true
      separator: '\.'
  - gen-files:
      scripts:
        - scripts/gen_features.py
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://installer.readthedocs.io/en/stable/objects.inv
          options:
            show_signature_annotations: true
            members_order: alphabetical
            separate_signature: true
      enable_inventory: true

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.blocks.admonition
  - pymdownx.keys:
      separator: +
      strict: false
      camel_case: false
  - pymdownx.tabbed:
      alternate_style: true
