name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12", "3.13", "3.14"]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --dev

      - name: Run frame-check-core tests
        run: uv run --directory frame-check-core pytest -v

  lint-and-benchmark:
    name: Lint and Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: true
      - name: Install dependencies
        run: uv sync --locked --dev
      - name: mypy check
        run: uv run mypy . --check-untyped-defs

      - name: Install ruff
        run: uv pip install ruff

      - name: Ruff Check
        run: ruff check --output-format=github .

      - name: Ruff Format
        run: ruff format --diff

      - name: Run the benchmarks
        if: ${{ !contains(github.event.head_commit.message, '[skip-bench]') }}
        uses: CodSpeedHQ/action@v4
        with:
          mode: instrumentation
          run: uv run pytest --codspeed
          token: ${{ secrets.CODSPEED_TOKEN }}

  pre-commit-ci:
    name: Pre-commit CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
