name: docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Cache uv
        uses: actions/cache@v4
        with:
          key: uv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          path: ~/.cache/uv
          restore-keys: |
            uv-${{ runner.os }}-

      - uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force
